EMPTY_DATA = "./Data/BBDDTrain/Vacio"

NUMBER_OF_CLUSTERS = 7
KMEANS_ROUTE = "./TrainedModels/KMeansModel.pkl"

POST_CLUSTERING_DIRECTORY_NAME = "./Data/BBDD_Clustered"

IMG_WIDTH = 384
IMG_HEIGHT = 256
INPUT_SHAPE = (IMG_HEIGHT, IMG_WIDTH, 3) # RGB color model

# Train RAE
BATCH_SIZE = 16
EPOCHS = 70
VERBOSE = 1
SEED = 1491